#!/bin/bash

# Set display resolution (uncomment for VM or specific resolution needs)
#wlr-randr --output Virtual-1 --mode 1920x1080 &

# Set wallpaper
swaybg -i $HOME/Backgrounds/beach.jpg -m fill &

# Start waybar
waybar -c ~/.config/waybar/config -s ~/.config/waybar/style.css &

# Polkit authentication agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Notification daemon
mako &

# Network manager applet
nm-applet &

# System monitoring
conky &

